timbre_res: MODELO papel timbrado FACET.docx
---
vice_coordenador: true
republicacao: false
extraordinaria: true
pdf_autosave: true
gdrive_save: false
---
path_local: ./resolucoes
path_drive_docx: G:/Meu Drive/Coordenadoria/Resoluções
path_drive_pdf: G:/Meu Drive/Documentos p  Assinatura PPGCTA/P  Assinar/Resoluções
final_directory_drive_pdf: 2026 - 02ª reunião (08-05-2026)
